### ISSUE TITLE
cluster-operator was blocked preventing new clusters creation

### ISSUE THREAD

**Issue by r7vme** [giantswarm/chart-operator#82] opened 2018-07-04 09:24 UTC
I've created new cluster in AWS, but aws-operator was not able to find encryption secret. It was missing, because cluster oprerator was blocked with another error/task for more that 30 minutes. Workaround was to restart cluster-operator.

Following error was repeated for a while (with increasing interval)

```
D 18-07-04T09:13:48.835395+0 attempt pinging tiller | helmclient/helmclient.go:206                                                                                                                 
D 18-07-04T09:13:48.838145+0 failed pinging tiller | helmclient/helmclient.go:232                                                                                                                  
        /go/src/github.com/giantswarm/cluster-operator/vendor/github.com/giantswarm/helmclient/helmclient.go:213:                                                                                  
        /go/src/github.com/giantswarm/cluster-operator/vendor/github.com/giantswarm/helmclient/helmclient.go:471:                                                                                  
        /go/src/github.com/giantswarm/cluster-operator/vendor/github.com/giantswarm/helmclient/helmclient.go:515: app=helm,name=tiller                                                            
        pod not found  
```

cc @rossf7 @fgimenez

**Comment by fgimenez** [comment] 2018-07-06 09:03
@r7vme could you please verify if this still happens? The issue was at the same time we had severe AWS problems (timeouts while recordsets).

**Comment by r7vme** [comment] 2018-07-06 11:56
I think it will be quite hard to reproduce. But if you  don't see obvious reasons for this issue and suspect aws api error, then i'm fine to close this issue. I can reopen if i'll see it.

**Comment by fgimenez** [comment] 2018-07-06 17:40
Ideally we should get to the root cause, but if it is hard to reproduce then it is not likely to hit us again? 

Looking at the logs in the description they seem to be debug messages that come from https://github.com/giantswarm/helmclient/blob/master/helmclient.go#L232. In case of an error in the backoff when trying to install tiller, we cancel the reconciliation here https://github.com/giantswarm/cluster-operator/blob/master/pkg/v5/resource/chart/create.go#L36-L44, this shouldn't block anything else. IMO there was something else that was causing the problem.

Maybe let's keep this issue open for a while, WDYT?

**Comment by fgimenez** [comment] 2018-07-20 09:22
No similar problems have been reported, closing for now feel free to reopen @r7vme

**Closed by fgimenez** 2018-07-20 09:22 UTC
